server:
 port: 9012    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
 client:
   serviceUrl:
    #defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
    defaultZone: ${EUREKA_URI:http://localhost:9015/eureka}
    healthcheck:
      enabled: true


spring:
 application:
   name: product-FPN   #current service name to be used by the eureka server
 main:
   allow-bean-definition-overriding: true
 data:
   mongodb:
     database: product-service_db-FPN
     port: 27017


